name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ master ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      # Nodeセットアップは任意（OryxでもOKだが再現性のため入れると安定）
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: next-azure/package-lock.json

      - name: Install & Build (Next.js)
        working-directory: next-azure
        run: |
          npm ci
          npm run build
      - name: Copy SWA config into artifact
        working-directory: next-azure
        run: cp staticwebapp.config.json .next/staticwebapp.config.json
      - name: Build And Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_PEBBLE_081F18910 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "next-azure"
          app_artifact_location: ".next"
          api_location: ""
          skip_api_build: true
          app_build_command: ""
          output_location: ""

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_PEBBLE_081F18910 }}
          action: close
